kpiwebapi/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from rest_framework_jwt import views
from kpi_manager import views as kpiviews

urlpatterns = [
    # url(r'', kpiviews.HomeIndexView.as_view(), name='home_page'),
    url(r'^home/', login_required(kpiviews.HomeIndexView.as_view()), name='home'),
    url(r'^my-kpi/print/(?P<year_request>[\w-]+)/(?P<month_request>[\w-]+)/$',
        login_required(kpiviews.StatisticTagView.as_view()), name='print'),
    url(r'^kpi/print/(?P<profile_id>[\w-]+)/(?P<year_request>[\w-]+)/(?P<month_request>[\w-]+)/$',
        login_required(kpiviews.MemberStatisticTagView.as_view()), name='member_print'),
    url(r'^kpi_admin/', admin.site.urls),
    url(r'', include('web_api.urls')),
    # url(r'^$', kpiviews.HomeIndexView.as_view(), name='home'),

    # url(r'^web-api/', include('web_api.urls', namespace='web_api')),

    # url(r'^account/', include('registration.urls', namespace='registration')),
    url(r'', include('registration.urls', namespace='registration')),
    url(r'^api-token-verify/', views.verify_jwt_token),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.conf.urls import url
# from django.contrib.auth import views as auth_views
# from django.views.generic import TemplateView
from rest_framework_jwt.views import ObtainJSONWebToken

# from kpiwebapi.views import register_api
from registration.serializers import CustomJWTSerializer
from . import views


urlpatterns = [
    url(r'^api/login/', ObtainJSONWebToken.as_view(serializer_class=CustomJWTSerializer)),
    url(r'^login/$', views.SiteLoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutThenLoginView.as_view(), name='logout'),
    # url(r'^register/', register_api),
    # url(r'^signup/$', views.RegisterView.as_view(), name='register'),

    # url(r'^password/reset/$', auth_views.password_reset,
    #     {'post_reset_redirect': 'registration:forgot_password_sent',
    #      'template_name': 'registration/forgot_password.html',  'password_reset_form': forms.ForgotPasswordForm},
    #     name='forgot_password'),

    # url(r'^password/reset/ok/$', TemplateView.as_view(template_name='registration/forgot_password_sent.html'),
    #     name='forgot_password_sent'),

    # url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.SitePasswordResetConfirmView.as_view(), name='forgot_password_confirm'),
    # url(r'^password/reset/complete/$',
    #     TemplateView.as_view(template_name='registration/forgot_password_complete.html'),
    #     name='password_reset_complete'),
]

web_api/urls.py
from django.conf.urls import url, include
from web_api.views import general_api, department, tag, task, work_time

from . import views

urlpatterns = [
    url(r'^api-info/', views.index_api_view),
    url(r'^web-api/', include([
        # GET: Thông tin hồ sơ
        url(r'^current-profile/get/$', general_api.get_user_api_view),

        # GET: Thông tin cá nhân của tôi
        url(r'^profile/info/$', department.get_my_profile_info_in_department,
            name='profile_info'),

        # GET: Thông tin cá nhân trực thuộc phòng ban
        url(r'^profile/info/specific/$', department.get_profile_info_specific_in_department,
            name='profile_info_specific'),  # Xong - đã phân quyền

        # GET: Thông tin cá nhân trực thuộc phòng ban
        url(r'^profile/list/no-pagination/$', department.get_profile_list_no_pagination_api_view,
            name='np_profile_list'),  # Xong - đã phân quyền

        # POST: Chỉnh sửa hồ sơ
        url(r'^profile/update/$', general_api.update_profile),

        # GET: Danh sách phòng ban
        url(r'^department/list/$', department.GetDepartmentListView.as_view(),
            name='department_list'),  # Xong - đã phân quyền

        # GET: Thông tin cá nhân trực thuộc phòng ban
        url(r'^department/list/no-pagination/$', department.get_department_list_no_pagination_api_view,
            name='np_department_list'),  # Xong - đã phân quyền

        # GET: Danh sách nhân viên trong một phòng ban
        url(r'^members/list/$', department.GetMemberInDepartmentListView.as_view(),
            name='member_list'),  # Xong - đã phân quyền

        # GET: Danh sách KPI của tất cả nhân viên
        url(r'^tag/list/$', tag.GetTagListView.as_view(),
            name='tag_list'),  # Xong - đã phân quyền

        # GET: Danh sách tất cả KPI của một nhân viên
        url(r'^tag/member/$', tag.GetAllTagOfMemberView.as_view(),
            name='tag_member'),  # Xong - đã phân quyền

        # GET: Danh sách tất cả KPI của tôi
        url(r'^my-tag/list/$', tag.GetMyTagView.as_view(),
            name='my_tag'),  # Xong

        # GET: Đếm tổng số KPI của tôi
        url(r'^my-tag/list/statistics/$', tag.get_my_tag_statistics_api_view,
            name='my_tag_statistics'),  # Xong

        # GET: Đếm tổng số KPI của một nhân viên
        url(r'^tag/member/list/statistics/$', tag.get_member_tag_statistics_api_view,
            name='tag_member_statistics'),  # Xong

        # GET: Đếm tổng số KPI của tất cả nhân viên
        url(r'^tag/list/statistics/$', tag.get_tag_statistics_api_view,
            name='tag_statistics'),  # Xong

        # GET: Một KPI của một nhân viên
        url(r'^tag/member/detail/$', tag.get_one_tag_of_member_detail_api_view,
            name='tag_member_detail'),  # Xong

        # POST: Tạo mới một KPI cho một nhân viên
        url(r'^new-tag/add/$', tag.add_new_tag_api_view,
            name='tag_add'),  # Xong - đã phân quyền

        # POST: Chỉnh sửa một KPI của một nhân viên
        url(r'^tag/member/edit/$', tag.edit_tag_member_api_view,
            name='tag_edit'),  # Xong - đã phân quyền

        # GET: Một KPI của tôi
        url(r'^my-tag/detail/$', tag.get_one_tag_detail_of_me_api_view,
            name='my_tag_detail'),  # Xong

        # GET: DS KPI của tôi dùng để tạo task
        url(r'^my-tag/list/no-pagination/$', tag.get_tag_list_of_me_no_pagination_api_view,
            name='np_my_tag'),  # Xong

        # POST: Chỉnh sửa một task của tôi
        url(r'^my-tag/edit/$', tag.edit_my_tag_api_view,
            name='my_tag_edit'),  # Xong

        # POST: Tính toán kết quả của Task và cập nhật vào Tag
        url(r'^my-tag/computation/$', tag.my_tag_computation_api_view,
            name='my_tag_computation'),  # Xong

        # GET: Danh sách tất cả Task của một KPI
        url(r'^task/list/$', task.GetTaskListView.as_view(),
            name='task_list'),  # Xong

        # GET: Danh sách tất cả Task của một KPI của tôi
        url(r'^my-task/list/$', task.GetMyTaskListView.as_view(),
            name='my_task_list'),  # Xong

        # GET: Một Task của một KPI
        url(r'^task/member/detail/$', task.get_one_task_of_member_detail_api_view,
            name='task_member_detail'),

        # POST: Thêm một Task mới của tôi
        url(r'^new-task/add/$', task.add_new_task_api_view,
            name='task_add'),  # Xong

        # POST: Chỉnh sửa một Task của tôi
        url(r'^my-task/edit/$', task.edit_my_task_api_view,
            name='my_task_edit'),  # Xong

        # GET: Một Task của một KPI của tôi
        url(r'^my-task/detail/$', task.get_one_task_detail_of_me_api_view,
            name='my_task_detail'),

        # GET: Danh sách tất cả Comment của một Task
        url(r'^task/comment/list/$', task.GetCommentOfTaskView.as_view(),
            name='task_comment_list'),

        # GET: Danh sách tất cả Comment của một Task của tôi
        url(r'^my-task/comment/list/$', task.GetCommentOfMyTaskView.as_view(),
            name='my_task_comment_list'),

        # POST: Tạo một comment mới trong Task của tôi
        url(r'^my-task/comment/add/$', task.add_comment_for_my_task_api_view,
            name='my_task_comment_add'),

        # POST: Tạo một comment mới trong Task của người khác
        url(r'^task/comment/add/$', task.add_comment_for_member_task_api_view,
            name='task_comment_add'),

        # POST: Chỉnh sửa hoặc xóa một comment trong Task của tôi
        url(r'^my-task/comment/edit/$', task.edit_comment_for_my_task_api_view,
            name='my_task_comment_add'),

        # GET: Giờ làm việc của một nhân viên
        url(r'^work-time/member/list/$', work_time.GetWordTimeMemberListView.as_view(),
            name='work_time_member_list'),

        # GET: Giờ làm việc của tôi
        url(r'^my-work-time/list/$', work_time.GetWordTimeListView.as_view(),
            name='my_work_time_list'),

        # POST: Thêm giờ làm việc mới của tôi
        url(r'^my-work-time/add/$', work_time.add_my_work_time_api_view,
            name='my_work_time_add'),

        # POST: Chỉnh sửa hoặc xóa giờ làm việc của tôi
        url(r'^my-work-time/edit/$', work_time.edit_my_work_time_api_view,
            name='my_work_time_edit'),

        # GET: Đếm tổng số giờ làm việc của một nhân viên trong tháng này
        url(r'^work-time/member/statistic/$', work_time.work_time_member_statistic_api_view,
            name='work_time_member_statistic'),

        # GET: Đếm tổng số giờ làm việc của tôi trong tháng này
        url(r'^my-work-time/statistic/$', work_time.my_work_time_statistic_api_view,
            name='my_work_time_statistic'),

        # POST: Đổi ảnh đại diện
        url(r'^avatar/upload/$', general_api.upload_avatar_api_view,
            name='avatar_upload'),
    ])),
]

templates/desktop/_global_footer.html
{% load static %}

<div class="container mt-4">
    <ul class="mobile-apps list-inline pb-2 mb-0">
        <li class="list-inline-item"><a href="https://itunes.apple.com/us/app/truyenyy-com/id1358215910" target="_blank"><i class="iconfont icon-apple"></i></a></li>
        <li class="list-inline-item"><a href="https://play.google.com/store/apps/details?id=com.truyenyy.apps.official2" target="_blank"><i class="iconfont icon-android"></i></a></li>
    </ul>
    <ul class="list-inline links">
        <li class="list-inline-item"><a target="_blank" href="#">Giới Thiệu</a></li>
        <li class="list-inline-item"><a target="_blank" href="#">Liên Hệ</a></li>
        <li class="list-inline-item"><a target="_blank" href="#">Điều Khoản Dịch Vụ</a></li>
        <li class="list-inline-item"><a target="_blank" href="#">Quy Định Riêng Tư</a></li>
{#        <li class="list-inline-item"><a target="_blank" href="{% url 'pages:detail' slug='van-de-ban-quyen' %}">Vấn Đề Bản Quyền</a></li>#}
{#        <li class="list-inline-item"><a target="_blank" href="https://truyenyy.com/sitemap.xml">Sitemap</a></li>#}
    </ul>
</div>

<a href="#" class="back-top" style="display: none;"><i class="iconfont icon-top"></i></a>

<hr>
<div class="container">
    <div class="row pt-md">
        <div class="col-lg-4 mb-5 mb-lg-0">
            <a href="/">
                <img src="{% static 'img/logo-black.svg' %}" alt="TruyenYY logo"
                     style="height: 40px;">
            </a>
            <div class="pb-1 ml-auto mr-auto small mt-2">
                TruyenYY (TruyệnYY hay gọi tắt "YY") là một <strong>nền tảng nội dung số</strong> trên internet,
                nơi thành viên có thể tự do xuất bản những
                nội dung tiếng Việt như: Tiểu thuyết, light novel, truyện ngắn hoặc thơ văn khác. Với những chức
                năng được cải tiến liên tục, TruyenYY sẽ
                mang lại cho Tác giả, Dịch giả và Người đọc những trải nghiệm tuyệt vời nhất.
                {% if not user.is_authenticated %}Đừng ngại đăng ký tài khoản tại TruyenYY, chỉ mất 30s và
                    hoàn toàn miễn phí.{% endif %}</div>
        </div>

    </div>
    <div class="row align-items-center justify-content-md-between py-4 mt-2 delimiter-top">
        <div class="col-md-6">
            <div class="copyright small font-weight-bold text-center text-md-left">
                &copy; 2012-{% now "Y" %} TruyenYY.com. All Rights Reserved.
            </div>
        </div>
        <div class="col-md-6">
            <ul class="nav justify-content-center justify-content-md-end mt-3 mt-md-0">
                <li class="nav-item">
                    <a class="nav-link" href="https://www.facebook.com/TruyenYY/" target="_blank" data-toggle="tooltip" title="Facebook Fanpage">
                        <img src="{% static 'img/logo-black.svg' %}" alt="Facebook" style="width: 24px; height: 24px;">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.facebook.com/groups/YYHoi/" target="_blank" data-toggle="tooltip" title="YY Hội">
                        <img src="{% static 'img/logo-black.svg' %}" alt="YY Hội" style="width: 24px; height: 24px;">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://twitter.com/TruyenYY/" target="_blank" data-toggle="tooltip" title="TruyenYY tại Twitter">
                        <img src="{% static 'img/logo-black.svg' %}" alt="Twitter" style="width: 24px; height: 24px;">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://www.youtube.com/TruyenYYOfficial" target="_blank" data-toggle="tooltip" title="Kênh Youtube Chính Thức TruyenYY">
                        <img src="{% static 'img/logo-black.svg' %}" alt="Youtube" style="width: 24px; height: 24px;">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://www.soundcloud.com/TruyenYY" target="_blank" data-toggle="tooltip" title="Kênh SoundClound Chính Thức TruyenYY">
                        <img src="{% static 'img/logo-black.svg' %}" alt="SoundCloud" style="width: 24px; height: 24px;">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/desktop/base.html
<!DOCTYPE html>{% load static %}
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}KPI Manager{% endblock %}</title>

    <meta name="description" content="{% block desc %}{% endblock %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block extra_meta %}{% endblock %}

{#    <link rel="manifest" href="{% url 'web_manifest' %}">#}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">#}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,700i&amp;subset=latin-ext,vietnamese" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400&amp;subset=latin-ext,vietnamese" rel="stylesheet">

    {% block media_head %}{% endblock %}
    {% block fb_zone %}{% endblock %}
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body {% block body_extra %}{% endblock %}>
{% block content %}{% endblock %}
</body>
</html>

templates/desktop/home.html
<!DOCTYPE html>{% load static %}
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>KPI Manager</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <link href="{% static 'home/index.e8858f33.css' %}" rel="stylesheet">
</head>
<body>
<div id="root"></div>
<script>
    {#var django_api_root_url = '{% build_site_url "/" %}';#}
    var django_login_url = '{% url "registration:login" %}';
</script>
<script src="{% static 'home/index.3c981286.js' %}"></script>
</body>

</html>